language: cpp
script:
  - export CXX="$CXX -isystem /usr/include/x86_64-linux-gnu/c++/4.8/ -isystem /usr/include/x86_64-linux-gnu"
  - mkdir build && cd build && ${CONFIGURE} && make VERBOSE=1
compiler:
  - gcc
  - clang
env:
#  - CONFIGURE="../autogen.sh"
  - CONFIGURE="cmake .."
before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo add-apt-repository -y "deb http://llvm.org/apt/saucy/ llvm-toolchain-saucy main"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get -qq install aptitude; sudo aptitude -yq2 update
  - sudo aptitude -yq2 full-upgrade -t trusty python
  - sudo aptitude -yq2 install -t trusty
      g++
      clang-3.4
      libboost1.54-all-dev
      cmake
      ninja-build
      libgl1-mesa-dev libegl1-mesa-dev libglu1-mesa-dev
notifications:
  email: false
